name: CI
on:
  push:
    paths:
      - '.github/workflows/az-cli-login.yml'
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true
    
    - run: |
        az account show
