name: Run Azure PostgresSQL Action Integration Tests

on:
  push:
    branches: test-postgresql

jobs:
  postgresql-action-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    steps:
      - uses: actions/checkout@v2
    
#       - uses: azure/login@v1
#         with:
#           creds: ${{ secrets.AZURE_CREDENTIALS }}
    
      - name: 'Azure Postgresql deploy'
        uses: Azure/postgresql@v1
        with:
          connection-string: ${{ secrets.POSTGRESQL_CONN_STRING }}
          server-name: "ak-flexible-postgres.postgres.database.azure.com"
          plsql-file: "run.sql"
