name: CI
on:
  push:
    paths: 
      - '.github/workflows/get-module.yml'
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: get path
      run: |
        echo $env::PSModulePath
        $env::PSModulePath=C:\Modules\
        echo $env::PSModulePath
        $m = Get-Module -Name Az.Accounts -ListAvailable | Sort-Object Version -Descending | Select-Object -First 1
        echo $m.Path
        echo $m.Version
      shell:
        pwsh
        
