name: CI
on:
  push:
    paths: 
      - '.github/workflows/get-module.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: get path
      run: |
        ls /usr/share | grep az
      shell:
        bash
        
