name: CI
on:
  push:
    paths: 
      - '.github/workflows/get-module.yml'
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: get path
      run: |
        ls C:\Modules\az_1.0.0
      
        
