name: CI
on:
  push:
    paths:
      - '.github/workflows/linux-container-kind-issue.yml'
  
jobs:
  build:
    name: 'Build job'
    runs-on: ubuntu-latest
    
    steps:
    - name: 'login to docker'
      uses: azure/docker-login@v1
      with:
        username: ${{secrets.REGISTRY_USERNAME}}
        password: ${{secrets.REGISTRY_PASSWORD}}
      
    - name: checkout repo
      uses: actions/checkout@v2.3.1
      
    - uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
      
    - name: webapps-deploy
      uses: azure/webapps-deploy@users/aksm-ms/linux-container-app-kind
      with:
        app-name: ak-test-linux-container
        publish-profile: ${{secrets.PUBLISH_PROFILE_CONTAINER}}
        images: ranjithr/mariohtml5:latest
