name: CI
on:
  push:
    paths:
      - '.github/workflows/ps.yml'
    
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: 'PS Commands'
      run: |
         echo "printing PSModulePath"
         echo $env:PSModulePath
         
         echo "setting module path in env var"
         #$env:PSModulePath = "/usr/share/:" + $env.PSModulePath
         #$env:PSModulePath = "C:\Modules\;" + $env.PSModulePath
         
         echo "printing PSModulePath again"
         echo $env:PSModulePath
         
         echo "running get module"
         Get-Module -Name Az.Accounts -ListAvailable | Sort-Object Version -Descending | Select-Object -First 1
      shell:
        pwsh
