name: CI
on:
  push:
    paths: 
      - '.github/workflows/main.yml'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - name: 'Azure PS login'
        uses: aksm-ms/login@master
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          enable-AzPSSession: true
