name: CI
on:
  push:
    paths:
      - '.github/workflows/ps.yml'
    
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: 'PS Commands'
      run: |
         echo "printing PSModulePath"
         $t = Measure-Command { echo $env:PSModulePath }
         echo "time taken - seconds: $($t.Seconds); milliseconds: $($t.Milliseconds)"
         echo "" 
         
         echo "setting module path in env var"
         #$env:PSModulePath = "/usr/share/:" + $env.PSModulePath
         $t = Measure-Command { $env:PSModulePath = "C:\Modules\;" + $env.PSModulePath }
         echo "time taken - seconds: $($t.Seconds); milliseconds: $($t.Milliseconds)"
         echo ""
         
         echo "printing PSModulePath again"
         $t = Measure-Command { echo $env:PSModulePath }
         echo "time taken - seconds: $($t.Seconds); milliseconds: $($t.Milliseconds)"
         echo ""
         
         echo "running get module"
         $t = Measure-Command { Get-Module -Name Az.Accounts -ListAvailable | Sort-Object Version -Descending | Select-Object -First 1 }
         echo "time taken - seconds: $($t.Seconds); milliseconds: $($t.Milliseconds)"
         echo ""
      shell:
        pwsh

