name: CI
on:
  push:
     paths:
      - '.github/workflows/win-2016.yml'
jobs:
  build:
    runs-on: windows-2016
    steps:
    - name: run PS commands
      run: |
        $env:PSModulePath="C:\Modules"
        Get-Module -Name Az.Accounts -ListAvailable | Sort-Object Version -Descending | Select-Object -First 1
      shell: powershell
