name: CI
on:
  push:
     paths:
      - '.github/workflows/win-2016-2.yml'
jobs:
  build:
    runs-on: windows-2016
    steps:
    - name: run PS commands
      run: |
        $env:PSModulePath="C:\Modules\az_4.3.0"
        $latestModule = Get-Module -Name Az.Accounts -ListAvailable | Sort-Object Version -Descending | Select-Object -First 1
        $version = $latestModule.Version.ToString()
        echo $version
        echo "Import-Module -Name C:\Modules\az_4.3.0\Az.Accounts\$version\Az.Accounts.psd1 -Global"
        Import-Module -Name C:\Modules\az_4.3.0\Az.Accounts\$version\Az.Accounts.psd1 -Global
      shell: powershell
