name: CI
on:
  push:
     paths:
      - '.github/workflows/win-2019.yml'
jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: run PS commands
      run: |
        $env:PSModulePath="C:\Modules\;$env:PSModulePath" 
        $latestModule = Get-Module -Name Az.Accounts -ListAvailable | Sort-Object Version -Descending | Select-Object -First 1
        $version = $latestModule.Version.ToString()
        echo $latestModule

        echo "Import-Module -Name $version.Path -Global"
        Import-Module -Name $version.Path -Global

        echo "Clear-AzContext -Scope Process"
        Clear-AzContext -Scope Process

        echo "Clear-AzContext -Scope CurrentUser -Force -ErrorAction SilentlyContinue"
        Clear-AzContext -Scope CurrentUser -Force -ErrorAction SilentlyContinue

        echo "Connect-AzAccount -ServicePrincipal -Tenant 72f988bf-86f1-41af-91ab-2d7cd011db47 -Credential (New-Object System.Management.Automation.PSCredential('586a5f0f-3720-42b2-82ef-d4479d53a0a5',(ConvertTo-SecureString /gk+ZqLp7E2PDrzuTvRg0Zju67ExLgAZ0wJisZaV6OM= -AsPlainText -Force))) -Environment AzureCloud"
        Connect-AzAccount -ServicePrincipal -Tenant 72f988bf-86f1-41af-91ab-2d7cd011db47 -Credential (New-Object System.Management.Automation.PSCredential('586a5f0f-3720-42b2-82ef-d4479d53a0a5',(ConvertTo-SecureString /gk+ZqLp7E2PDrzuTvRg0Zju67ExLgAZ0wJisZaV6OM= -AsPlainText -Force))) -Environment AzureCloud

        echo "Set-AzContext -SubscriptionId c94bda7a-0577-4374-9c53-0e46a9fb0f70 -TenantId 72f988bf-86f1-41af-91ab-2d7cd011db47"
        Set-AzContext -SubscriptionId c94bda7a-0577-4374-9c53-0e46a9fb0f70 -TenantId 72f988bf-86f1-41af-91ab-2d7cd011db47
        
        echo "Get-AzRecoveryServicesVault -ResourceGroupName ch-test1"
        Get-AzRecoveryServicesVault -ResourceGroupName ch-test1

      shell: powershell
