name: CI
on:
  push:
     paths:
      - '.github/workflows/win-2019.yml'
jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: run PS commands
      run: |
        ls C:\Modules\az_*\Az.Accounts\*
        # ls C:\Modules\az_4.3.0\Az.Accounts\
      shell: powershell
